### ISSUE TITLE
column widths not the same as original CSS

### ISSUE THREAD

**Issue by jmaddi** [whatsnewsaes/Skeleton-Sass#3]
Hi,

This is more of a question - but how come the column widths in this SASS (and also LESS) project seem to be so different to those in the original CSS?

For example, the original skeleton.css reads:
```css
  .one.column,
  .one.columns                    { width: 4.66666666667%; }
  .two.columns                    { width: 13.3333333333%; }
  .three.columns                  { width: 22%;            }
  .four.columns                   { width: 30.6666666667%; }
  .five.columns                   { width: 39.3333333333%; }
  .six.columns                    { width: 48%;            }
  .seven.columns                  { width: 56.6666666667%; }
  .eight.columns                  { width: 65.3333333333%; }
  .nine.columns                   { width: 74.0%;          }
  .ten.columns                    { width: 82.6666666667%; }
  .eleven.columns                 { width: 91.3333333333%; }
  .twelve.columns                 { width: 100%; margin-left: 0; }
```

But the SCSS file compiles to:
```css
  .container .one.column,
  .container .one.columns {
    width: 6.83333%;
  }
  .container .two.columns {
    width: 15.16667%;
  }
  .container .three.columns {
    width: 23.5%;
  }
  .container .four.columns {
    width: 31.83333%;
  }
  .container .five.columns {
    width: 40.16667%;
  }
  .container .six.columns {
    width: 48.5%;
  }
  .container .seven.columns {
    width: 56.83333%;
  }
  .container .eight.columns {
    width: 65.16667%;
  }
  .container .nine.columns {
    width: 73.5%;
  }
  .container .ten.columns {
    width: 81.83333%;
  }
  .container .eleven.columns {
    width: 90.16667%;
  }
  .container .twelve.columns {
    width: 100%;
    margin-left: 0;
  }
```
